[build]
  publish = "public"
  command = "gatsby build"

[build.environment]
  NODE_VERSION = "20"
  NETLIFY_USE_YARN = "true"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs]
  output_path = "reports/lighthouse.html"

[[plugins]]
  package = "@netlify/plugin-gatsby"

[[headers]]
  for = "/*"
  [headers.values]
    cache-control = "public, max-age=2592000"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Robots-Tag = "index"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Vary = "Accept-Encoding"
    Permissions-Policy = "accelerometer=(), ambient-light-sensor=(), camera=(), encrypted-media=(self), fullscreen=(self), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), midi=(), payment=(), picture-in-picture=(self), usb=(), vibrate=(), vr=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self' data:; connect-src 'self' https://www.google-analytics.com https://www.googletagmanager.com; frame-src 'self'; object-src 'none'; form-action 'self'"

[[headers]]
  for = "/static/*"
  [headers.values]
    cache-control = "public, max-age=31536000"
